language: node_js
node_js:
- 4.1.2
services:
- mongodb
before_install:
- npm install -g grunt-cli
install:
- npm install
before_script:
- grunt build
deploy:
  provider: heroku
  api_key:
    secure: Y59xehcV6zZPQ8V+V2IGkMisVs5WzE0neTB/TeblQZwbWhS+kOYecizM4jyEn7NEmhfptHDqX+ZPMiZkbgua3jFVPEmmDwDeXisWKmU7HKX3SnenI8yuJYjUP5kE74MTjsO32/L4hkpPFqULTBoTlUo0MmgkWkIwNA3D8XIyg6USXMKouo+l97H9lZ32hCp+3R4GWO+vaKjbGr8L3rTZx1D3VxcgDEZ97j8YHxhNM7XKcUCNKKwPWLlGbSBjzqyeWaAvCZV1/V73FHz2JNSHigOlaI+u2nLRHRNVkgpSLP7e95hmHJV6T854dRTgISHPCTCpuCq1Wd16Izl4m+M//CbKpyG5V+mNDclSyD5So1Y5SELB/ZjOoVjRfN4/WNrK63gB5hh1aWkQUNFnGLeEFg926rzQ4OaJJmKJOzoTVQoATUf5JofufRhaOw58HjP4/FbAtnNcpNSSMhagqQynXSF/hi7k1HYfian7zmcqNjl3Mq9Jll2+39RHfkmq33BIr1RarQO0vfWVqgMXk748XGq1Kee1tax933Sk0HSlGmxihPvEwfv+u+fIyZ9DabUTw0rR6aIDeAfSXghfsl9248imDWNgYzd8yG/8IgnaxJKYBd+jiUA4+yfFWqzQ7EGi1dJNgcDaf52m2+2cpF9+Aiz1VXwImiSF+WrchTFsD/E=
  app:
    production: sodocan
    master: sodocan-staging
  on:
    repo: sodocan/sodocan.js
