language: node_js
node_js:
- 4.1.2
services:
- mongodb
before_install:
- npm install -g grunt-cli
install:
- npm install
deploy:
  provider: heroku
  api_key:
    secure: ce4MnZ1bGxPCcyZCKUJvPu/hNuorIg75kREMI5ggDqHh4exylVFbcMD6GtWjxPrvdthbBBxgYQbYbGTDz20VacO1CN/aQemUyB13OcAf7HUR1SMeZxobSiC+I0eFNvQDnl5PDOCNyanejjfUJHN5saerM1T34vDIGOPJDaqDwSRktTUZeTOHWtTxdPqnGeu/x2x42dppOo5B0ocyvyHLRzrlcWHW1IhtHU70ar4IwPYdGXHdib/4Dp8O8P3KDD2C1WH+J6Wxf08AnSGZZr1lnFXiOBNjUhdz2SVn8OUEREkdxB4rW1XWjOolZ8TlcpUHc5QrU1LWYQ+umRWs/3AMmgI49Jf7mhQD8guCz7xKIOdh6i0Q0bQ/83a+N7fZ/zCN8EyAk+Uqej3+Mb8kWrwupQXKpU/bbDCn2nlwZ+sCOWB/slg/RXbBs1x+nDlVL+NXsWvPaVlprK+yLQjlKtuNKewOS0E1U0rAhvcMSYg1t4Mf0rR+1SjABAtTmrFD51ljbbA4IotejvpO8rfIn4qzE0J3ZpZvD4jsTKUu/0IsEhJHFw0ixZcaBe2D5nYefx4ukIynPztiMQS0DjE4efHz3jTLkpCR13CBWRu+fepbnOCMfifyRlqY2FbEggkwWthOeK48ValKvT41uqOKZlAeJexG1lk8F9AdgreWNWJZPS0=
  app:
    production: sodocan
    master: sodocan-staging
  on:
    repo: sodocan/sodocan.js
