language: node_js
node_js:
- 4.1.2
services:
- mongodb
before_install:
- npm install -g grunt-cli
install:
- npm install
before_script:
- grunt build
deploy:
  provider: heroku
  api_key:
    production: ihe+u5FuiAn+KVg8b8dkTRA0We92aAhxN/GqNgJYe8IRcdkRFxacGqC6DGeQBWYzP987nm6egFm7pcPQYAJ+NnQM37+x+yExBhQjxrECcA3/d8jEfY8zTIKZ1bnkPEGD+xuliGHInII/GddZ0hZzd2lN4jD0+HjctFiqqtWNqCQkmLvB+P6WTBQqQsVZWb832AiKCLRhU+9ctDoCTOeJcx4gu8wOHIM/gC2HNqfmN7RRvYPnQAsE0ghQMGWteWvzg5BHkhba4jrjF1aTPSgU0AWwif33vxXrT7CmwmPCLtCQchCuctgbdQ++JoB+eXuZnytSF78OZAA3H698iyuQIyXYmVpYorpv5orxkj2rqNr2hu8Tv+uTQNg82+uthBJH7hIC3GtxsIddvajBLQryPCH/TRVOnfpLE+GD/t6KxrDEzy05lRo8hRbDj/1arR2/Fm1yIoRKPaVQMTfkQIOLsajXxiNbm+44l32Y5FTadVdqGwXqStGdUYD+J+0nKRycbjAzM/a2MLGkIKvtXjwBFLgv6NZ5ktd5fn/RdWuRlWhw8U1GH8QxDcmChUI0X1mkGFxnoZ2PFNp1fVae6TIVsh+tLo+he7TLle6KwV5MRm2zeg65LaL1qh+hECVj44dVfM+eVjIV0Jt33EC+0sO0NxbHPmTSAfDhx068A2DFYBU=
    master: bDlIocZm0Ckly1fwDRKw3IRN9HHYOlgRDLeWgYivW7+DSVQFILEva5BxiJ0+ODBGtPXGIZGoLJY7Oq5eqzeYAi2wMMXDOtKlXbq+B2Vq+W6LQSV1I3RgKp6zq20mwgcxWQaMiIEHYtkAjbTYegVa1idLjQKZ+5XUvnSGGM/uk0vL89pTCSduxjzOalEDMCzb67a5bgFYV+J/9qOJyvMfj+HFIpkzsU4lNmmMdc3uJk/TQoEAokpOPc5Q0a4V9eFxfwexX/0C0PtH8Gxr0QSqrOqwg8Jm9DRM/2E9XciCR6tLeh28IisW1+ZUbWuMX2o0J/uQOK2LQ3rylNv1Cf1nW440dm8JvyDrqRD72xmWGlF4XLuj1n+18wcszJuPJA40jw1I2NFg1+snL8dHTwEmWVBkO3zVlpmZDBdobtwJuhh8UgtWikhZzb9l67zPnhQarBFIVhR+kwuTd+4tqDr4nAlrWaFYwLmrf5q9L4GvgNqzsWLv1MTu+YCA2vlv3Rygl6LH/bJjpILCPvgawUEE/WHquhExSiNCmKgAWk4QEqORiRi7r7P9sFbxT8k0KX4UUEM6q9O6x09WeqA3gDsLszbIarLIC5y0755D8Hv6MQRTSGoHy7+WeZf0Ng8O51FEdMSlzk5vBs2iYxW9GqWBTtLY/lre2UdyYmE4i7I73Pc=
  app:
    production: sodocan
    master: sodocan-staging
  on:
    repo: sodocan/sodocan.js
